apiVersion: v1
kind: Service
metadata:
  name: bass
  namespace: instruments
  labels:
    app: bass
    service: bass
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: instruments
  name: bass-v1
  labels:
    app: bass
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bass
      version: v1
  template:
    metadata:
      labels:
        app: bass
        version: v1
    spec:
      serviceAccountName: instruments-sa
      containers:
        - name: bass
          image: gregerrag/istio-instrument
          ports:
            - containerPort: 8080
          env:
            - name: INSTRUMENT_ID
              value: "bass-v1"
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: instruments
    name: bass-v2
    labels:
      app: bass
      version: v2
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: bass
        version: v2
    template:
      metadata:
        labels:
          app: bass
          version: v2
      spec:
        serviceAccountName: instruments-sa
        containers:
          - name: bass
            image: gregerrag/istio-instrument
            ports:
              - containerPort: 8080
            env:
              - name: INSTRUMENT_ID
                value: "bass-v2"
