apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: instruments
  name: hh-v1
  labels:
    app: hh
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hh
      version: v1
  template:
    metadata:
      labels:
        app: hh
        version: v1
    spec:
      serviceAccountName: instruments-sa
      containers:
        - name: hh
          image: gregerrag/istio-instrument
          ports:
            - containerPort: 8080
          env:
            - name: INSTRUMENT_ID
              value: "hh1"
---
apiVersion: v1
kind: Service
metadata:
  name: hh
  namespace: instruments
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: hh
