apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: instruments
  name: kicksnare-v1
  labels:
    app: kicksnare
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kicksnare
      version: v1
  template:
    metadata:
      labels:
        app: kicksnare
        version: v1
    spec:
      serviceAccountName: instruments-sa
      containers:
        - name: kicksnare
          image: gregerrag/istio-instrument
          ports:
            - containerPort: 8080
          env:
            - name: INSTRUMENT_ID
              value: "kicksnare1"
---
apiVersion: v1
kind: Service
metadata:
  name: kicksnare
  namespace: instruments
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: kicksnare
