apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: instruments
  name: pad-v1
  labels:
    app: pad
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pad
      version: v1
  template:
    metadata:
      labels:
        app: pad
        version: v1
    spec:
      serviceAccountName: instruments-sa
      containers:
        - name: pad
          image: gregerrag/istio-instrument
          ports:
            - containerPort: 8080
          env:
            - name: INSTRUMENT_ID
              value: "pad1"
---
apiVersion: v1
kind: Service
metadata:
  name: pad
  namespace: instruments
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: pad
