apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: instruments
  name: piano-v1
  labels:
    app: piano
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piano
      version: v1
  template:
    metadata:
      labels:
        app: piano
        version: v1
    spec:
      serviceAccountName: instruments-sa
      containers:
        - name: piano
          image: gregerrag/istio-instrument
          ports:
            - containerPort: 8080
          env:
            - name: INSTRUMENT_ID
              value: "piano1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: instruments
  name: piano-v2
  labels:
    app: piano
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piano
      version: v2
  template:
    metadata:
      labels:
        app: piano
        version: v2
    spec:
      serviceAccountName: instruments-sa
      containers:
        - name: piano
          image: gregerrag/istio-instrument
          ports:
            - containerPort: 8080
          env:
            - name: INSTRUMENT_ID
              value: "piano2"
---
apiVersion: v1
kind: Service
metadata:
  name: piano
  namespace: instruments
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: piano
