apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: instruments
  name: rhodes-v1
  labels:
    app: rhodes
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhodes
      version: v1
  template:
    metadata:
      labels:
        app: rhodes
        version: v1
    spec:
      serviceAccountName: instruments-sa
      containers:
        - name: rhodes
          image: gregerrag/istio-instrument
          ports:
            - containerPort: 8080
          env:
            - name: INSTRUMENT_ID
              value: "rhodes1"
---
apiVersion: v1
kind: Service
metadata:
  name: rhodes
  namespace: instruments
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: rhodes
