apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: player-backend-gateway
  namespace: hack-istio-player-backend
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: player-backend-vs
  namespace: hack-istio-player-backend
spec:
  hosts:
  - "*"
  gateways:
  - player-backend-gateway
  http:
  - match:
    - uri:
        prefix: /instrument
    - uri:
        prefix: /instrument-file
    route:
    - destination:
        port:
          number: 8080
        host: player-backend
