apiVersion: v1
kind: Namespace
metadata:
  name: instruments
---
apiVersion: v1
kind: Namespace
metadata:
  name: player-backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: player-ui
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: player-backend-sa
  namespace: player-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instruments-sa
  namespace: instruments
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: player-ui-sa
  namespace: player-ui
