apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: player-ui
  name: player-ui
  labels:
    app: player-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-ui
  template:
    metadata:
      labels:
        app: player-ui
    spec:
      serviceAccountName: player-ui-sa
      containers:
      - name: player-ui
        image: pfust75/player-ui:latest
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: player-ui
  namespace: player-ui
  labels:
    app: player-ui
    service: player-ui
spec:
  ports:
  - port: 80
    targetPort: 4200
    name: http
  selector:
    app: player-ui
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: player-ui-gateway
  namespace: player-ui
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: player-ui-vs
  namespace: player-ui
spec:
  hosts:
  - "*"
  gateways:
  - player-ui-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        port:
          number: 80
        host: player-ui
    
